import { db } from "../db";

const NOW =
  "(to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))";

/** Migration 13: many photos per order, each optionally tied to one color. orders.image_url stays as the cover photo. */
export async function migrateOrderPhotos() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=13").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS order_photos(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      image_url TEXT NOT NULL,
      color TEXT NOT NULL DEFAULT '',
      position BIGINT NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      UNIQUE(order_id,image_url));
    INSERT INTO order_photos(order_id,image_url,color,position)
      SELECT id,image_url,'',0 FROM orders WHERE image_url IS NOT NULL
      ON CONFLICT DO NOTHING;
    CREATE INDEX IF NOT EXISTS order_photos_order ON order_photos(order_id,position);
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (13)").run();
}
