import { db } from "../db";

const NOW =
  "(to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))";

/** Migration 14: results of Kiểm NPL/Vải and Kiểm rập. Recorded for history; they do not block cutting. */
export async function migratePreparationChecks() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=14").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS preparation_checks(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      stage TEXT NOT NULL CHECK(stage IN ('kiem_npl','kiem_rap')),
      result TEXT NOT NULL CHECK(result IN ('dat','dat_co_ghi_chu','khong_dat')),
      defect_qty BIGINT NOT NULL DEFAULT 0 CHECK(defect_qty>=0),
      notes TEXT NOT NULL DEFAULT '',
      checked_by TEXT REFERENCES employees(id) DEFERRABLE INITIALLY IMMEDIATE,
      checked_on TEXT NOT NULL,
      actor_id TEXT NOT NULL,
      represented_id TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW});
    CREATE INDEX IF NOT EXISTS preparation_checks_order ON preparation_checks(order_id,stage,id);
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (14)").run();
}

/** Migration 15: pattern check details (version, sizes, pieces, measurements, approver). */
export async function migratePatternCheckDetails() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=15").get()
  )
    return;
  await db.exec(`
    ALTER TABLE preparation_checks
      ADD COLUMN IF NOT EXISTS pattern_version TEXT NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS sizes_checked TEXT NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS pieces_expected BIGINT,
      ADD COLUMN IF NOT EXISTS pieces_received BIGINT,
      ADD COLUMN IF NOT EXISTS measurements TEXT NOT NULL DEFAULT '[]',
      ADD COLUMN IF NOT EXISTS approved_by TEXT REFERENCES employees(id) DEFERRABLE INITIALLY IMMEDIATE;
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (15)").run();
}

/** Migration 16: per-order pattern spec sheet (measurement points and standard values from the tech pack). */
export async function migratePatternSpecs() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=16").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS pattern_specs(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      position BIGINT NOT NULL DEFAULT 0,
      point TEXT NOT NULL,
      size TEXT NOT NULL DEFAULT '',
      spec DOUBLE PRECISION NOT NULL CHECK(spec>=0),
      tolerance DOUBLE PRECISION NOT NULL DEFAULT 0.5 CHECK(tolerance>=0),
      UNIQUE(order_id,point,size));
    CREATE INDEX IF NOT EXISTS pattern_specs_order ON pattern_specs(order_id,position);
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (16)").run();
}

/** Migration 17: photos of problems found during a preparation check (product_images URLs, JSON array). */
export async function migratePreparationPhotos() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=17").get()
  )
    return;
  await db.exec(
    "ALTER TABLE preparation_checks ADD COLUMN IF NOT EXISTS photos TEXT NOT NULL DEFAULT '[]'",
  );
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (17)").run();
}

/** Migration 18: POM chart layout — sheet unit/sizes/base size per order, POM code per row, unit per check. */
export async function migratePomSheet() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=18").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS pattern_sheets(
      order_id TEXT PRIMARY KEY REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      unit TEXT NOT NULL DEFAULT 'inch' CHECK(unit IN ('inch','cm')),
      sizes TEXT NOT NULL DEFAULT '[]',
      base_size TEXT NOT NULL DEFAULT '');
    ALTER TABLE pattern_specs ADD COLUMN IF NOT EXISTS code TEXT NOT NULL DEFAULT '';
    ALTER TABLE preparation_checks ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT 'cm';
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (18)").run();
}

/** Migration 19: a check is either measured against the POM chart or a written assessment only. */
export async function migrateCheckMode() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=19").get()
  )
    return;
  await db.exec(
    "ALTER TABLE preparation_checks ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'measure' CHECK(mode IN ('measure','text'))",
  );
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (19)").run();
}

/** Migration 20: which stage of the sample/production a pattern check belongs to ('' = not recorded). */
export async function migrateCheckPhase() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=20").get()
  )
    return;
  await db.exec(
    "ALTER TABLE preparation_checks ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT '' CHECK(phase IN ('','rap_thu','fit','pps','bulk'))",
  );
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (20)").run();
}

/** Migration 21: a check can be confirmed by a photo of the filled sheet or by an attached file (PDF/Excel/Word). */
export async function migrateCheckAttachments() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=21").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS preparation_files(
      id TEXT PRIMARY KEY,
      owner_id TEXT NOT NULL REFERENCES accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
      name TEXT NOT NULL,
      mime TEXT NOT NULL,
      size BIGINT NOT NULL,
      data BYTEA NOT NULL,
      created_at BIGINT NOT NULL);
    CREATE INDEX IF NOT EXISTS preparation_files_owner ON preparation_files(owner_id);
    ALTER TABLE preparation_checks ADD COLUMN IF NOT EXISTS files TEXT NOT NULL DEFAULT '[]';
    ALTER TABLE preparation_checks DROP CONSTRAINT IF EXISTS preparation_checks_mode_check;
    ALTER TABLE preparation_checks ADD CONSTRAINT preparation_checks_mode_check CHECK(mode IN ('measure','text','photo','file'));
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (21)").run();
}
