export const baseSchema = `
  CREATE TABLE IF NOT EXISTS lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    leader_name TEXT NOT NULL,
    workers_count BIGINT NOT NULL,
    capacity_per_day BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS employees (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    line_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    phone TEXT
  );

  CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    customer TEXT NOT NULL,
    product_code TEXT NOT NULL,
    product_name TEXT NOT NULL,
    image_url TEXT,
    total_quantity BIGINT NOT NULL DEFAULT 0,
    line_id BIGINT NOT NULL DEFAULT 1,
    order_date TEXT NOT NULL,
    deadline TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'normal',
    assigned_to TEXT NOT NULL,
    current_stage TEXT NOT NULL DEFAULT 'nhan_don',
    progress BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'on_track',
    notes TEXT,
    created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))
  );

  CREATE TABLE IF NOT EXISTS order_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    quantity BIGINT NOT NULL DEFAULT 0,
    cut_qty BIGINT NOT NULL DEFAULT 0,
    sewn_qty BIGINT NOT NULL DEFAULT 0,
    qc_passed_qty BIGINT NOT NULL DEFAULT 0,
    packed_qty BIGINT NOT NULL DEFAULT 0,
    delivered_qty BIGINT NOT NULL DEFAULT 0,
    UNIQUE(order_id, color, size)
  );

  CREATE TABLE IF NOT EXISTS order_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    stage_key TEXT NOT NULL,
    stage_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    assignee TEXT,
    received_qty BIGINT NOT NULL DEFAULT 0,
    completed_qty BIGINT NOT NULL DEFAULT 0,
    remaining_qty BIGINT NOT NULL DEFAULT 0,
    started_at TEXT,
    completed_at TEXT,
    notes TEXT,
    UNIQUE(order_id, stage_key)
  );

  CREATE TABLE IF NOT EXISTS production_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    employee_name TEXT NOT NULL,
    line_id BIGINT NOT NULL,
    order_id TEXT NOT NULL,
    product_name TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    stage TEXT NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price NUMERIC NOT NULL,
    total_pay NUMERIC NOT NULL,
    updated_by TEXT NOT NULL,
    month TEXT NOT NULL,
    is_locked BIGINT NOT NULL DEFAULT 0,
    created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))
  );

  CREATE TABLE IF NOT EXISTS payroll_locks (
    month TEXT PRIMARY KEY,
    locked_by TEXT NOT NULL,
    locked_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS')),
    notes TEXT
  );

  CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))
  );

  CREATE TABLE IF NOT EXISTS qc_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    inspected_qty BIGINT NOT NULL,
    passed_qty BIGINT NOT NULL,
    defect_qty BIGINT NOT NULL,
    defect_type TEXT,
    rework_qty BIGINT NOT NULL DEFAULT 0,
    reinspected_qty BIGINT NOT NULL DEFAULT 0,
    repassed_qty BIGINT NOT NULL DEFAULT 0,
    inspector TEXT NOT NULL,
    created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))
  );
`;
