import { db } from "../db";

const NOW =
  "(to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh', 'YYYY-MM-DD HH24:MI:SS'))";

/** Migration 12: materials (NPL/vải) and defect attribution to the worker who made the piece. */
export async function migrateWorkshopExtras() {
  if (
    await db.prepare("SELECT 1 FROM schema_migrations WHERE version=12").get()
  )
    return;
  await db.exec(`
    CREATE TABLE IF NOT EXISTS order_materials(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      name TEXT NOT NULL, unit TEXT NOT NULL,
      required_qty NUMERIC NOT NULL DEFAULT 0 CHECK(required_qty>=0),
      notes TEXT NOT NULL DEFAULT '', created_by TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      UNIQUE(order_id,name));
    CREATE TABLE IF NOT EXISTS material_movements(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_id BIGINT NOT NULL REFERENCES order_materials(id) DEFERRABLE INITIALLY IMMEDIATE,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      kind TEXT NOT NULL CHECK(kind IN ('receive','defect','use','return')),
      quantity NUMERIC NOT NULL CHECK(quantity>0),
      movement_date TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '',
      actor_id TEXT NOT NULL, represented_id TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW});
    CREATE INDEX IF NOT EXISTS material_movement_order ON material_movements(order_id,material_id);
    CREATE TABLE IF NOT EXISTS defect_attributions(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      operation_id BIGINT NOT NULL REFERENCES operation_records(id) DEFERRABLE INITIALLY IMMEDIATE,
      order_id TEXT NOT NULL REFERENCES orders(id) DEFERRABLE INITIALLY IMMEDIATE,
      color TEXT NOT NULL, size TEXT NOT NULL,
      employee_id TEXT NOT NULL REFERENCES employees(id) DEFERRABLE INITIALLY IMMEDIATE,
      stage TEXT NOT NULL, quantity BIGINT NOT NULL CHECK(quantity>0),
      created_at TEXT NOT NULL DEFAULT ${NOW});
    CREATE INDEX IF NOT EXISTS defect_attribution_worker ON defect_attributions(employee_id,order_id);
  `);
  await db.prepare("INSERT INTO schema_migrations(version) VALUES (12)").run();
}
